version: "2.4"

services:

  # main service
  talebook:
    restart: always
    image: talebook/talebook
    volumes:
      - /tmp/dev:/data
      - /Users/talebook/codes/talebook/webserver:/var/www/talebook/webserver
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
